#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -b|--backend-branch)
    MDM_APPLICATION_BRANCH="$2"
    shift # past argument
    shift # past value
    ;;
    -f|--frontend-branch)
    MDM_UI_BRANCH="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

##################
# Functions

getDate(){
  date +"%Y-%m-%d %H:%M:%S,%sZ"
}

outputLine(){
  echo
  eval printf '%.0s-' {1..$(tput cols)}
  echo
}

##################
# Build Args
BUILD_ARGS="--build-arg CACHE_BURST=$(date +%s)"

if [ -n "$MDM_APPLICATION_BRANCH" ]
then
  echo "Using backend branch $MDM_APPLICATION_BRANCH"
  BUILD_ARGS="$BUILD_ARGS --build-arg MDM_APPLICATION_COMMIT=${MDM_APPLICATION_BRANCH}"
fi

if [ -n "$MDM_UI_BRANCH" ]
then
  echo "Using frontend branch $MDM_UI_BRANCH"
  BUILD_ARGS="$BUILD_ARGS --build-arg MDM_UI_COMMIT=${MDM_UI_BRANCH}"
fi

##################

set -e

outputLine

echo "Using docker >> $(docker --version) << [Required 19.03.0+]"
echo "Using docker-compose >> $(docker-compose -version) << [Recommended 1.27.0+]"

outputLine

echo "$(getDate) : Rebuilding docker compose"
echo
docker-compose build ${BUILD_ARGS}

outputLine

echo "$(getDate) : Restarting docker compose"
echo
docker-compose up -d