#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -b|--backend-branch)
    MDM_APPLICATION_BRANCH="$2"
    shift # past argument
    shift # past value
    ;;
    -f|--frontend-branch)
    MDM_UI_BRANCH="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

##################

BUILD_ARGS="--build-arg CACHE_BURST=$(date +%s)"

if [ -n "$MDM_APPLICATION_BRANCH" ]
then
  echo "Using backend branch $MDM_APPLICATION_BRANCH"
  BUILD_ARGS="$BUILD_ARGS --build-arg MDM_APPLICATION_COMMIT=${MDM_APPLICATION_BRANCH}"
fi

if [ -n "$MDM_UI_BRANCH" ]
then
  echo "Using frontend branch $MDM_UI_BRANCH"
  BUILD_ARGS="$BUILD_ARGS --build-arg MDM_UI_COMMIT=${MDM_UI_BRANCH}"
fi

##################

set -e

echo "Rebuilding docker compose"
echo
docker-compose build $BUILD_ARGS
docker-compose up -d